# -*- coding: utf-8 -*-
"""
Pydantic Schemas for Recommendation Endpoints (Content, Collaborative, Hybrid, Spatial, Cold-Start, & MMR Diversification)
"""

from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field


class ContentPreferenceRequest(BaseModel):
    """
    Request payload for Mode B: Preference-to-Restaurant recommendation.
    """
    preferred_cuisines: Optional[Union[List[str], str]] = Field(
        default=None,
        description="Preferred Indian/regional cuisines, e.g. ['South Indian', 'Karnataka'] or 'North Indian, Mughlai'"
    )
    preferred_price_tier: Optional[str] = Field(
        default=None,
        description="Budget, Moderate, Premium, or Luxury"
    )
    preferred_type: Optional[str] = Field(
        default=None,
        description="Dining format, e.g. 'Quick Bites', 'Casual Dining', 'Cafe', 'Bakery'"
    )
    preferred_area: Optional[str] = Field(
        default=None,
        description="Target Bengaluru locality, e.g. 'Koramangala 5th Block', 'Indiranagar', 'Jayanagar'"
    )
    max_cost_for_two: Optional[int] = Field(
        default=None,
        ge=0,
        description="Maximum cost for two in INR (₹)"
    )
    min_rating: Optional[float] = Field(
        default=None,
        ge=1.0,
        le=5.0,
        description="Minimum average rating filter [1.0, 5.0]"
    )
    online_order_only: Optional[bool] = Field(
        default=False,
        description="Filter for restaurants offering online ordering"
    )
    book_table_only: Optional[bool] = Field(
        default=False,
        description="Filter for restaurants offering table booking"
    )
    top_k: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Number of recommendations to return (1 to 50)"
    )


class RestaurantRecommendationItem(BaseModel):
    """
    Single recommended restaurant item from Content-Based Recommender.
    """
    restaurant_id: int
    name: str
    content_score: float
    similarity_score: float
    rating: Optional[float] = None
    review_count: int
    cuisines: str
    restaurant_type: str
    area: str
    address: str
    price_tier: str
    cost_for_two_inr: int
    online_order: bool
    book_table: bool
    location_source: str = "Bengaluru locality centroid"
    location_precision: str = "locality-level"


class RecommendationResponse(BaseModel):
    """
    Response envelope for Content-Based recommendations.
    """
    status: str = "success"
    query_type: str
    count: int
    recommendations: List[RestaurantRecommendationItem]


class CollaborativeRecommendationItem(BaseModel):
    """
    Single recommended restaurant item from Collaborative Filtering (Surprise SVD).
    """
    restaurant_id: int
    name: str
    predicted_rating: float
    rating: Optional[float] = None
    review_count: int
    cuisines: str
    restaurant_type: str
    area: str
    address: str
    price_tier: str
    cost_for_two_inr: int
    online_order: bool
    book_table: bool
    location_source: str = "Bengaluru locality centroid"
    location_precision: str = "locality-level"
    model_source: str = "collaborative_svd_synthetic_benchmark"


class CollaborativeRecommendationResponse(BaseModel):
    """
    Response envelope for Collaborative Filtering recommendations.
    """
    status: str = "success"
    user_id: int
    model_source: str = "collaborative_svd_synthetic_benchmark"
    count: int
    disclaimer: str = "Predictions generated by Surprise SVD trained on the Synthetic Collaborative Filtering Benchmark."
    recommendations: List[CollaborativeRecommendationItem]


class NearbyRecommendationItem(BaseModel):
    """
    Single restaurant item returned by Spatial Search Engine.
    """
    restaurant_id: int
    name: str
    distance_km: float
    rating: Optional[float] = None
    review_count: int
    cuisines: str
    restaurant_type: str
    area: str
    address: str
    cost_for_two_inr: int
    price_tier: str
    online_order: bool
    book_table: bool
    latitude: float
    longitude: float
    location_source: str = "Bengaluru locality centroid"
    location_precision: str = "locality-level"


class NearbyRecommendationResponse(BaseModel):
    """
    Response envelope for Spatial Nearby queries.
    """
    status: str = "success"
    latitude: float
    longitude: float
    radius_km: Optional[float] = None
    count: int
    recommendations: List[NearbyRecommendationItem]


class PopularRecommendationItem(BaseModel):
    """
    Single restaurant item returned by Bayesian Popularity Engine.
    """
    restaurant_id: int
    name: str
    popularity_score: float
    rating: Optional[float] = None
    review_count: int
    cuisines: str
    restaurant_type: str
    area: str
    address: str
    cost_for_two_inr: int
    price_tier: str
    online_order: bool
    book_table: bool
    location_source: str = "Bengaluru locality centroid"
    location_precision: str = "locality-level"


class PopularRecommendationResponse(BaseModel):
    """
    Response envelope for Popularity cold-start queries.
    """
    status: str = "success"
    scope: str = "global"
    count: int
    recommendations: List[PopularRecommendationItem]


class OnboardingRequest(BaseModel):
    """
    Cold-start onboarding questionnaire payload.
    """
    favorite_cuisines: List[str] = Field(..., min_length=1, description="List of favorite cuisines")
    preferred_dining_types: Optional[List[str]] = Field(default=None, description="Preferred dining formats")
    preferred_area: Optional[str] = Field(default=None, description="Preferred Bengaluru neighborhood")
    price_tier: Optional[str] = Field(default="Moderate", description="Budget, Moderate, Premium, Luxury")
    max_budget_for_two: Optional[int] = Field(default=None, ge=0, description="Max cost for two in INR")
    is_pure_veg_preferred: Optional[bool] = Field(default=False, description="Pure veg preference")
    online_ordering: Optional[bool] = Field(default=False, description="Online delivery preference")
    latitude: Optional[float] = Field(default=None, ge=-90.0, le=90.0, description="Optional user latitude")
    longitude: Optional[float] = Field(default=None, ge=-180.0, le=180.0, description="Optional user longitude")
    top_k: int = Field(default=10, ge=1, le=50, description="Number of recommendations")
    mmr_enabled: Optional[bool] = Field(default=True, description="Enable MMR diversification")
    mmr_lambda: Optional[float] = Field(default=0.75, ge=0.0, le=1.0, description="MMR relevance-diversity tradeoff")


class DiversityMetrics(BaseModel):
    """
    Recommendation set diversity metrics envelope.
    """
    top_k: int
    unique_cuisine_ratio: float
    unique_restaurant_type_ratio: float
    unique_locality_ratio: float
    avg_pairwise_similarity: float
    intra_list_diversity: float
    redundancy_rate: float
    mean_relevance: float
    relevance_retention_pct: float
    relevance_drop_pct: float


class DiversificationMetadata(BaseModel):
    """
    Metadata summarizing diversification algorithm execution.
    """
    enabled: bool
    method: str = "MMR"
    lambda_param: float = 0.75
    diversity_metrics: Optional[DiversityMetrics] = None


class HybridRecommendationItem(BaseModel):
    """
    Single recommended restaurant item from Hybrid Recommender with multi-component scores and explainability.
    """
    restaurant_id: int
    name: str
    hybrid_score: float
    content_score: float
    collaborative_score: float
    location_score: float
    quality_score: float
    mmr_score: Optional[float] = None
    distance_km: Optional[float] = None
    rating: Optional[float] = None
    review_count: int
    cuisines: str
    restaurant_type: str
    area: str
    address: str
    price_tier: str
    cost_for_two_inr: int
    online_order: bool
    book_table: bool
    location_source: str = "Bengaluru locality centroid"
    location_precision: str = "locality-level"
    model_source: str = "hybrid"
    is_unrated: Optional[bool] = False
    imputed_rating_prior: Optional[float] = None
    explanation: str
    explanation_metadata: Optional[Dict[str, Any]] = None


class HybridRecommendationResponse(BaseModel):
    """
    Response envelope for Hybrid recommendations.
    """
    status: str = "success"
    user_id: Optional[int] = None
    is_cold_start: bool
    strategy: Optional[str] = None
    model_source: str = "hybrid"
    effective_weights: Dict[str, float]
    count: int
    diversification: Optional[DiversificationMetadata] = None
    recommendations: List[HybridRecommendationItem]


class HybridRecommendationRequest(BaseModel):
    """
    Request payload for POST /api/v1/recommendations/hybrid.
    """
    user_id: Optional[int] = Field(default=None, description="Optional user ID for personalized SVD collaborative signal")
    target_restaurant_id: Optional[int] = Field(default=None, description="Optional restaurant ID for item-to-item similarity")
    preferred_cuisines: Optional[Union[List[str], str]] = Field(default=None, description="Preferred cuisines list or comma-separated string")
    preferred_price_tier: Optional[str] = Field(default=None, description="Budget, Moderate, Premium, Luxury")
    preferred_type: Optional[str] = Field(default=None, description="Quick Bites, Casual Dining, Cafe, etc.")
    preferred_area: Optional[str] = Field(default=None, description="Target Bengaluru neighborhood")
    latitude: Optional[float] = Field(default=None, ge=-90.0, le=90.0, description="User latitude for distance proximity decay")
    longitude: Optional[float] = Field(default=None, ge=-180.0, le=180.0, description="User longitude for distance proximity decay")
    radius_km: Optional[float] = Field(default=None, ge=0.1, le=50.0, description="Optional maximum search radius in kilometers")
    max_cost_for_two: Optional[int] = Field(default=None, ge=0, description="Hard budget constraint in INR")
    min_rating: Optional[float] = Field(default=None, ge=1.0, le=5.0, description="Hard minimum rating constraint")
    online_order_only: Optional[bool] = Field(default=False, description="Hard filter for online order capability")
    book_table_only: Optional[bool] = Field(default=False, description="Hard filter for table booking capability")
    custom_weights: Optional[Dict[str, float]] = Field(default=None, description="Optional custom weights")
    mmr_enabled: Optional[bool] = Field(default=True, description="Enable MMR diversification")
    mmr_lambda: Optional[float] = Field(default=0.75, ge=0.0, le=1.0, description="MMR relevance-diversity tradeoff parameter")
    top_k: int = Field(default=10, ge=1, le=50, description="Number of recommendations to return")
