[theme]
primaryColor = "#01875f"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#202124"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
